CREATE TABLE USUARIOS(
  id SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (id)
);

CREATE TABLE ESTATUS(
    id_estatus SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ESTATUS PRIMARY KEY (id_estatus)
);

CREATE TABLE ESTUDIANTES (
  id_estudiante SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  matricula INT(7) NOT NULL,
  nombre VARCHAR(30) NOT NULL,
  apellidoPaterno VARCHAR(30) NOT NULL,
  apellidoMaterno VARCHAR(30) NOT NULL,
  semestre TINYINT(2) NOT NULL,
  fechaIngreso DATE,
  estatus SMALLINT(6) UNSIGNED NOT NULL,
  CONSTRAINT UC_ESTUDIANTE1 UNIQUE (matricula),
  CONSTRAINT UC_ESTUDIANTE2 UNIQUE (nombre, apellidoPaterno, apellidoMaterno),
  CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (id_estudiante),
  CONSTRAINT FOREIGN KEY (estatus) REFERENCES ESTATUS (id_estatus) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MATERIAS (
  id_materias SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  clave INT(7) NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  requires INT(7),
  semestre TINYINT(2) NOT NULL,
  CONSTRAINT UC_MATERIA1 UNIQUE (clave, nombre),
  CONSTRAINT UC_MATERIA2 UNIQUE (nombre),
  CONSTRAINT PK_MATERIA PRIMARY KEY (id_materias),
  CONSTRAINT FOREIGN KEY (requires) REFERENCES MATERIAS (clave) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE FRECUENCIAS(
  id_frecuencias SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  frecuencia INT(6) NOT NULL,
  diaSemana VARCHAR(20) NOT NULL,
  requires VARCHAR(100),
  CONSTRAINT UC_FRECUENCIA UNIQUE (diaSemana),
  CONSTRAINT PK_FRECUENCIA PRIMARY KEY (id_frecuencias)
);

CREATE TABLE MAESTROS (
   id_maestros SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
   matricula INT(7) NOT NULL,
   nombre VARCHAR(30) NOT NULL,
   apellidoPaterno VARCHAR(30) NOT NULL,
   apellidoMaterno VARCHAR(30) NOT NULL,
   fechaIngreso DATE,
   estatus SMALLINT(6) UNSIGNED NOT NULL,
   CONSTRAINT PK_MAESTROS PRIMARY KEY (id_maestros),
   CONSTRAINT UC_MAESTROS_MATRICULA UNIQUE (matricula),
   CONSTRAINT UC_MAESTROS_NOMBRE UNIQUE (nombre, apellidoPaterno, apellidoMaterno),
   CONSTRAINT FOREIGN KEY (estatus) REFERENCES ESTATUS (id_estatus) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE CURSOS (
  id_curso SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  materia INT(7) NOT NULL,
  maestro INT(7) NOT NULL,
  semestre TINYINT(2) NOT NULL,
  grupo TINYINT(2) NOT NULL,
  frecuencia SMALLINT(6) UNSIGNED NOT NULL,
  horaInicio TIME NOT NULL,
  horaFin TIME NOT NULL,
  CONSTRAINT PK_CURSOS PRIMARY KEY (id_curso),
  CONSTRAINT UC_CURSOS UNIQUE (materia, maestro, semestre, frecuencia, horaInicio, horaFin),
  CONSTRAINT FK_CURSOS_MATERIA FOREIGN KEY (materia) REFERENCES MATERIAS (clave) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_CURSOS_MATERIA_SEMESTRE FOREIGN KEY (semestre) REFERENCES MATERIAS (semestre) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_CURSOS_MAESTRO FOREIGN KEY (maestro) REFERENCES MAESTROS (matricula) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_CURSOS_FRECUENCIA FOREIGN KEY (frecuencia) REFERENCES FRECUENCIAS (id_frecuencias) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE INSCRIPCIONES (
  id_inscripcion SMALLINT(6) UNSIGNED AUTO_INCREMENT NOT NULL,
  matricula INT(7) NOT NULL,
  curso SMALLINT(6) UNSIGNED NOT NULL,
  estatus SMALLINT(6) UNSIGNED NOT NULL,
  CONSTRAINT PK_INCRIPCION PRIMARY KEY (id_inscripcion),
  CONSTRAINT UC_INSCRIPCION UNIQUE (matricula, curso),
  CONSTRAINT FK_INSCRIPCION_MATRICULA FOREIGN KEY (matricula) REFERENCES ESTUDIANTES (matricula) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_INSCRIPCION_CURSO FOREIGN KEY (curso) REFERENCES CURSOS (id_curso) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_INSCRIPCION_ESTATUS FOREIGN KEY (estatus) REFERENCES ESTATUS(id_estatus) ON DELETE CASCADE ON UPDATE CASCADE
);
