CREATE VIEW ESTADO_ESTUDIANTES AS SELECT ESTUDIANTES.matricula,
CONCAT(ESTUDIANTES.nombre, " ", ESTUDIANTES.apellidoPaterno, " ", ESTUDIANTES.apellidoMaterno) AS "Estudiante",
ESTUDIANTES.semestre, ESTATUS.nombre
FROM ESTUDIANTES
INNER JOIN ESTATUS ON ESTUDIANTES.estatus = ESTATUS.id_estatus;

CREATE VIEW VISTA_CURSOS AS SELECT CURSOS.id_curso, CONCAT(MAESTROS.nombre, " ", MAESTROS.apellidoPaterno, " ",
  MAESTROS.apellidoMaterno) AS "MAESTRO", MATERIAS.nombre AS MATERIA,
  CURSOS.semestre, CURSOS.grupo AS GRUPO,
  FRECUENCIAS.diaSemana, CURSOS.horaInicio, CURSOS.horaFin FROM CURSOS
INNER JOIN MAESTROS ON CURSOS.maestro = MAESTROS.matricula
INNER JOIN MATERIAS ON CURSOS.materia = MATERIAS.clave
INNER JOIN FRECUENCIAS ON CURSOS.frecuencia = FRECUENCIAS.id_frecuencias;

CREATE VIEW VISTA_INSCRIPCIONES AS SELECT INSCRIPCIONES.id_inscripcion AS "ID", ESTUDIANTES.matricula,
CONCAT(ESTUDIANTES.nombre, " ", ESTUDIANTES.apellidoPaterno, " ", ESTUDIANTES.apellidoMaterno) AS "Estudiante",
INSCRIPCIONES.curso, MATERIAS.nombre, CURSOS.grupo, CURSOS.horaInicio, CURSOS.horaFin
FROM INSCRIPCIONES
INNER JOIN ESTUDIANTES ON INSCRIPCIONES.matricula = ESTUDIANTES.matricula
INNER JOIN CURSOS ON INSCRIPCIONES.curso = CURSOS.id_curso
INNER JOIN MATERIAS ON CURSOS.materia = MATERIAS.clave;
